// new message arrival
#define NTLN_NOTIFICATION_NEW_MESSAGE @"NTLN_NOTIFICATION_NEW_MESSAGE"

// message has been marked as read
#define NTLN_NOTIFICATION_MESSAGE_STATUS_MARKED_AS_READ @"NTLN_NOTIFICATION_MESSAGE_STATUS_MARKED_AS_READ"

// message view change
#define NTLN_NOTIFICATION_MESSAGE_VIEW_CHANGING @"NTLN_NOTIFICATION_MESSAGE_VIEW_CHANGING"
#define NTLN_NOTIFICATION_MESSAGE_VIEW_CHANGED @"NTLN_NOTIFICATION_MESSAGE_VIEW_CHANGED"